#pragma once

#include <cstddef>
#include <cmath>
#include <cassert>

#include "qf/PathGeneration/PathGenerator.hpp"
#include "qf/PathGeneration/SimulationGrid.hpp"
#include "qf/Payoffs/Payoff.hpp"
#include "qf/Pricing/PricingResult.hpp"
#include "qf/Simulation/MonteCarloEngine.hpp"
#include "qf/Simulation/MonteCarloSettings.hpp"
#include "qf/Simulation/SimulationResult.hpp"
#include "qf/Statistics/RunningStats.hpp"
#include "qf/Random/RandomGenerator.hpp"

namespace qf
{
    /**
     * @brief Monte Carlo pricing engine.
     *
     * Prices financial derivatives by simulating paths of the underlying
     * asset and evaluating the supplied payoff.
     *
     * The pricing engine is parameterized by a stochastic model that
     * governs path evolution and a payoff that determines the option's
     * terminal value.
     *
     * Option sensitivities (Greeks) are estimated using central finite
     * differences with Common Random Numbers (CRN) to reduce estimator
     * variance.
     *
     * The returned standard error represents the statistical uncertainty
     * of the Monte Carlo price estimate.
     *
     * @tparam Model Stochastic model used to generate asset price paths.
     */
    template<typename Model>
    class MonteCarloPricer
    {
    public:
        /**
         * @brief Constructs a Monte Carlo pricing engine.
         *
         * Creates a pricing engine that estimates the present value of a
         * derivative by simulating asset price paths generated by the supplied
         * stochastic model and evaluating the specified payoff.
         *
         * The pricing engine stores references to the supplied model, random
         * number generator, and payoff. These objects must remain valid for
         * the lifetime of the pricing engine.
         *
         * @param model Stochastic model used to generate asset price paths.
         * @param randomGenerator Random number generator used during path simulation.
         * @param payoff Payoff evaluated at the end of each simulated path.
         * @param spot Initial underlying asset price.
         * @param riskFreeRate Continuously compounded annual risk-free interest rate.
         * @param maturity Time to expiry in years.
         * @param requestedTimeStep Targeted simulation time step in years.
         * @param simulations Number of Monte Carlo simulations to perform.
         *
         * @pre spot > 0
         * @pre riskFreeRate >= 0
         * @pre maturity > 0
         * @pre requestedTimeStep > 0
         * @pre requestedTimeStep <= maturity
         * @pre simulations > 0
         */
        MonteCarloPricer(
            const Model& model,
            RandomGenerator& randomGenerator,
            const Payoff& payoff,
            double spot,
            double riskFreeRate,
            double maturity,
            const MonteCarloSettings& settings) noexcept
            : m_model(model)
            , m_randomGenerator(randomGenerator)
            , m_payoff(payoff)
            , m_spot(spot)
            , m_riskFreeRate(riskFreeRate)
            , m_maturity(maturity)
            , m_settings(settings)
            , m_simulationGrid(m_maturity, settings.RequestedTimeStep)
        {
            assert(spot > 0.0 &&
                "spot must be greater than zero");

            assert(riskFreeRate >= 0.0 &&
                "riskFreeRate must be non-negative");

            assert(maturity > 0.0 &&
                "maturity must be greater than zero");

            assert(settings.RequestedTimeStep > 0.0 &&
                "requestedTimeStep must be greater than zero");

            assert(settings.RequestedTimeStep <= maturity &&
                "requestedTimeStep must be smaller than or equal to maturity");
        }

    public:
        /**
         * @brief Estimates the option price using Monte Carlo simulation.
         *
         * Simulates independent asset price paths, evaluates the payoff for
         * each path and discounts the estimated expected payoff to the
         * present value.
         *
         * A cloned random number generator is used so repeated calls produce
         * identical results when the underlying generator state is unchanged.
         *
         * @return Estimated option value and its standard error.
         */
        [[nodiscard]]
        PricingResult Price() const
        {
            RandomGenerator randomGenerator = m_randomGenerator.Clone();

            return PriceImplementation(
                m_model,
                randomGenerator,
                m_spot,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid,
                m_settings
            );
        }

        /**
         * @brief Estimates Delta using a central finite difference.
         *
         * Two Monte Carlo simulations are performed using bumped spot
         * prices. Common Random Numbers are used to reduce the variance
         * of the finite difference estimator.
         *
         * @param bump Absolute perturbation applied to the spot price.
         *
         * @return Estimated Delta.
         */
        [[nodiscard]]
        double Delta(double bump) const 
        {
            const PricingResult up = PriceScenario(
                m_model,
                m_spot + bump,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            );

            const PricingResult down = PriceScenario(
                m_model,
                m_spot - bump,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            ); 

            return
                (up.Value - down.Value)
                /
                (2.0 * bump); 
        }

        /**
         * @brief Estimates Gamma using a central finite difference.
         *
         * Three Monte Carlo simulations are performed using bumped  and current spot
         * prices. Common Random Numbers are used to reduce the variance
         * of the finite difference estimator.
         *
         * @param bump Absolute perturbation applied to the spot price.
         *
         * @return Estimated Gamma.
         */
        [[nodiscard]]
        double Gamma(double bump) const 
        {
            const PricingResult up = PriceScenario(
                m_model,
                m_spot + bump,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            );

            const PricingResult middle = PriceScenario(
                m_model,
                m_spot,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            );

            const PricingResult down = PriceScenario(
                m_model,
                m_spot - bump,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            );

            return
                (up.Value - 2.0 * middle.Value + down.Value)
                /
                (bump * bump);
        }

        /**
         * @brief Estimates Vega using a central finite difference.
         *
         * Two Monte Carlo simulations are performed using bumped model
         * volatilities. Common Random Numbers (CRN) are used to reduce the
         * variance of the finite difference estimator.
         *
         * @param bump Absolute perturbation applied to the model volatility.
         *
         * @return Estimated Vega.
         */
        [[nodiscard]]
        double Vega(double bump) const
        {
            Model upModel(m_model.Drift(), m_model.Volatility() + bump);
            Model downModel(m_model.Drift(), m_model.Volatility() - bump);

            const PricingResult up = PriceScenario(
                upModel,
                m_spot,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            ); 

            const PricingResult down = PriceScenario(
                downModel,
                m_spot,
                m_riskFreeRate,
                m_maturity,
                m_simulationGrid
            );

            return
                (up.Value - down.Value)
                /
                (2.0 * bump);
        }

        /**
         * @brief Estimates Rho using a central finite difference.
         *
         * Two Monte Carlo simulations are performed using bumped
         * continuously compounded risk-free interest rates. Common Random
         * Numbers (CRN) are used to reduce the variance of the finite
         * difference estimator.
         *
         * @param bump Absolute perturbation applied to the risk-free
         * interest rate.
         *
         * @return Estimated Rho.
         */
        [[nodiscard]]
        double Rho(double bump) const
        {
            Model upModel(m_riskFreeRate + bump, m_model.Volatility());
            Model downModel(m_riskFreeRate - bump, m_model.Volatility());

            const PricingResult up = PriceScenario(
                upModel,
                m_spot,
                m_riskFreeRate + bump,
                m_maturity,
                m_simulationGrid
            ); 

            const PricingResult down = PriceScenario(
                downModel,
                m_spot,
                m_riskFreeRate - bump,
                m_maturity,
                m_simulationGrid
            );

            return
                (up.Value - down.Value)
                /
                (2.0 * bump);
        }

        /**
         * @brief Estimates Theta using a central finite difference.
         *
         * Two Monte Carlo simulations are performed using shorter and
         * longer times to expiry. Common Random Numbers (CRN) are used to
         * reduce the variance of the finite difference estimator.
         *
         * @param bump Absolute perturbation applied to the time to expiry,
         * expressed in years.
         *
         * @return Estimated Theta.
         */
        [[nodiscard]]
        double Theta(double bump) const
        {
            // NOTE:
            //
            // Theta constructs separate simulation grids for the bumped maturities.
            // The number of time steps may therefore differ between the two scenarios.
            // This is acceptable for the current implementation but may be revisited
            // when the Risk module is introduced.
            double shorterMaturity = m_maturity - bump; 
            double longerMaturity = m_maturity + bump; 

            SimulationGrid shorterGrid(shorterMaturity, m_settings.RequestedTimeStep);
            SimulationGrid longerGrid(longerMaturity, m_settings.RequestedTimeStep);

            const PricingResult shorter = PriceScenario(
                m_model,
                m_spot,
                m_riskFreeRate,
                shorterMaturity,
                shorterGrid
            ); 

            const PricingResult longer = PriceScenario(
                m_model,
                m_spot,
                m_riskFreeRate,
                longerMaturity,
                longerGrid
            );

            return
                (shorter.Value - longer.Value)
                /
                (2.0 * bump); 
        }


    private:
        [[nodiscard]]
        PricingResult PriceScenario(
            const Model& model,
            double spot,
            double riskFreeRate,
            double maturity,
            SimulationGrid simulationGrid) const
        {
            RandomGenerator randomGenerator = m_randomGenerator.Clone(); 

            return PriceImplementation(
                model,
                randomGenerator,
                spot,
                riskFreeRate,
                maturity,
                simulationGrid,
                m_settings
            );
        }

        [[nodiscard]]
        PricingResult PriceImplementation(
            const Model& model,
            RandomGenerator& randomGenerator,
            double spot,
            double riskFreeRate,
            double maturity,
            SimulationGrid simulationGrid,
            MonteCarloSettings settings) const
        {
            SimulationResult simulationResult = m_engine.Simulate(model, randomGenerator, m_payoff, spot, simulationGrid, settings);

            const double discountFactor = std::exp(-riskFreeRate * maturity);

            PricingResult result;

            result.Value = discountFactor * simulationResult.Mean; 

            result.StandardError = discountFactor * simulationResult.StandardError; 

            return result;
        }

    private:
        const Model& m_model;
        RandomGenerator& m_randomGenerator;

        const Payoff& m_payoff;

        double m_spot = 0.0;
        double m_riskFreeRate = 0.0;
        double m_maturity = 0.0;
        double m_timeStep = 0.0;

        const MonteCarloSettings& m_settings;
        SimulationGrid m_simulationGrid; 
        MonteCarloEngine<Model> m_engine;
    };
}